### PR TITLE
rename Estaimpuis to steenput for name_nl

### PR DESCRIPTION
**Pull request by JensTimmerman**
https://nl.wikipedia.org/wiki/Steenput 
 De Franse naam Estaimpuis van dit plaatsje is een fonetische nabootsing van het woord Steenput.

### CODE REVIEW

**Comment by JensTimmerman** [comment]
I guess you will want to add this to join_data instead of the resulting json...

**Comment by JensTimmerman** [comment]
Pont-à-Celles is with capital C

**Comment by bmesuere** [comment]
The goal is indeed not to modify the result file manually. Those names come from the REFNIS file from statbel.
Step one would be to verify that the statbel is indeed wrong, step two would be to add a replace to the join script, step three is to ask statbel why this is wrong.

**Comment by JensTimmerman** [comment]
mail sent to statbel, I noticed they mention their sources : https://www.bpost2.be/zipcodes/files/zipcodes_alpha_nl_new.pdf and https://ec.europa.eu/eurostat/web/nuts/local-administrative-units
Both of them don't include dutch name for gembloux or estaimpuis, but does have Pont-à-Celles witch capital C

**Comment by JensTimmerman** [comment]
Statbel confirmed they will look into this and update their file if needed or present me with an answer if not.

**Comment by JensTimmerman** [comment]
```
Voor de publicatie van de gegevens in verband met de gemeentecodes (REFNIS codes), baseren we ons op de gemeentenamen zoals in de wet opgenomen.
De Nederlandstalige benamingen voor Estaimpuis en Gembloux zijn hierin niet opgenomen. Vandaar dat we deze benamingen ook niet opgenomen hebben in de tabellen op onze website.

Het moet inderdaad Pont-à-Celles zijn (en niet Pont-à-celles). We zullen het nodige doen om de tabellen op onze website aan te passen.

Met vriendelijke groeten,

xxx  xxxxxxxxx


Statbel (Algemene Directie Statistiek – Statistics Belgium)
Dienst Nomenclaturen
```

Pont-à-celles will be changd to Pont-à-Celles in the statbell files ; steenput and gemblours do not legally exist

**Comment by JensTimmerman** [comment]
Do I create a separate issue for Pont-à-celles or will this be automatically picked up once statbell fixes their tables?

**Comment by bmesuere** [comment]
Should be fixed automatically if they update the table and I readd the file. This isn't a problem right now because I do a case insensitive match to generate the file.

**Pull request closed without merging**
